### ISSUE TITLE
Support ecto 3

### ISSUE THREAD

**Issue by archSeer** [deadtrickster/prometheus-ecto#12]
One thing not stated in ecto 3 release notes is that it seems to remove the `loggers:` configuration key in favour of using https://github.com/elixir-telemetry/telemetry

https://hexdocs.pm/ecto/Ecto.Repo.html#module-telemetry-events

**Comment by akoutmos** [comment]
Also looking forward to a new release :)

**Comment by th31nitiate** [comment]
Any information on how to access this version would more than welcome :), would this have to be from the repository I guess

**Comment by archSeer** [comment]
Listing as a git dependency works fine for us:

```elixir
{:prometheus_ecto, git: "https://github.com/deadtrickster/prometheus-ecto"}
```

https://hexdocs.pm/mix/Mix.Tasks.Deps.html

**Comment by akoutmos** [comment]
If you want to lock the dependency to a certain commit you can also do 
```Elixir
{:prometheus_ecto, github: "deadtrickster/prometheus-ecto", ref: "650a403183f6a2fb6b682d7fbcba8bf9d24fe1e4"}
```

**Comment by deadtrickster** [comment]
1.4.0

**Comment by akoutmos** [comment]
Thanks a million!!
