### ISSUE TITLE
1.4.3 release?

### ISSUE THREAD

**Issue by halostatue** [deadtrickster/prometheus-ecto#23]
I’m currently encountering a telemetry error (the handler is stopping) in my tests because `entry.queue_time` is causing a `:badkey` error. PR #22 fixes this, but I’d prefer not specifying a git version of `prometheus_ecto` for this.

If we can get a point release, this would fix my issue.

**Comment by deadtrickster** [comment]
Pushed!

**Comment by halostatue** [comment]
Thanks!
