### ISSUE TITLE
update prometheus_ex dependency to 2.0 ?

### ISSUE THREAD

**Issue by happysalada** [deadtrickster/prometheus-ecto#5]
the current depdency is on 1.X, maybe update to 2.0 if there are no problems ?
(if it's just making a PR, I don't mind doing it)

**Comment by deadtrickster** [comment]
it can work with both 1.x and 2.x and 3.x. Mix supports this case, like here: https://github.com/elixir-plug/plug/blob/master/mix.exs#L41

I would say it's just tweaking mix.exs, yes.

**Comment by deadtrickster** [comment]
I guess I can close this.
